image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Initialize terraform
    init: |
      export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
      export AWS_SECRET_ACCESS_KEY="$AWS_SECRETS_ACCESS_KEY"
      export AWS_DEFAULT_REGION="us-west-2"
    command: |
      # terraform init
      # terraform plan

vscode:
  extensions:
    - hashicorp.terraform