site_name: TF+Gitlab Lunch and Learn
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
repo_url: https://github.com/tredfield/terraform-lnl
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.details
nav:
  - Home: index.md
  - Setup: setup.md
  - Basic Terraform Project: basic.md
  - Update and Add Resources: update-and-add.md