site_name: TF+Gitlab Lunch and Learn
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.footer
    - navigation.sections    
    - header.autohide    
  palette:
    scheme: slate
    primary: blue
    accent: light blue
  logo: assets/slalom-logo-black-150x50.png
  favicon: https://slalom.com/themes/custom/slalom/favicon.ico
extra:
  homepage: https://slalom.com
repo_url: https://gitlab.com/slalom-test/terraform-lnl
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - attr_list
  - md_in_html  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
nav:
  - Home: index.md
  - What is Terraform: what-is-tf.md
  - Why Use Terraform: why-tf.md
  - Why Choose Terraform: why-choose-tf.md
  - Terraform 101: tf-101.md
  - Setup: setup.md
  - Basic Terraform Project: basic.md
  - Update and Add Resources: update-and-add.md
  - Gitlab Pipelines: gitlab.md
  - Questions and Answers: q-n-a.md